### ISSUE TITLE
is not working 

### ISSUE THREAD

**Issue by GatoAmarilloBicolor** [unarix/haiku_darkstyle#1]
i am on a x86_64 with hrev54361.
did try the binaries does'nt work, i did compile with make and before it compile i had to erase the dark theme first, then it get compiled, but didnt work yet.

The options appear on te apearence configurator but when i choose them dont apply, no decorator and no flat control working here.

**Comment by unarix** [comment]
Hello @skarmiglione! Do you restart the deskbar and tracker services after set the decorator and controllok?

> Restart:
> You need to restart the computer or quit "Deskbar" and "Tracker" services from "ProcessControler" (they will restart auto).
