### ISSUE TITLE
Upstreaming

### ISSUE THREAD

**Issue by kallisti5** [unarix/haiku_darkstyle#11]
@unarix   I'm thinking about merging FlatControlLook and FlatDecorator into the default Haiku images.

Thoughts?  The style is pretty good, and we need a few built-in choices pretty badly.  I think there's room for the scroll bars to be slightly more visible under the default light theme, but overall it's the best community decor / control_look theme i've seen so far.

**Comment by kallisti5** [comment]
https://review.haiku-os.org/c/haiku/+/4508 was opened placing the current decorators / control_looks into the under-utilized haiku_extras package

**Comment by unarix** [comment]
Thank you very much for appreciating the work! I think there are many things that can be optimized in that code, feel free to modify what is necessary or suggest any changes that you consider. Go ahead with the merge! I will try to help as much as I can while my free time allows it. Rgrds.
