### ISSUE TITLE
Visual issue after compile the GIT version

### ISSUE THREAD

**Issue by CalebCDE** [unarix/haiku_darkstyle#15]
Hi
## Issue
When compile the decorator everything seems to go fine but when i'm trying to use the tab title and the edge of the window are in blue, regardless of what they have configured in the appearance menu.

Replicated in haiku_x86 hrev57377 and HAIKU X86_64 hrev57367 by the User Nexus6h in the Telegram Group today.

## Screenshots of the issue
![sc1](https://github.com/unarix/haiku_darkstyle/assets/14283509/1d445cbb-33c9-48b6-bf29-05d3c00b1980)

![sc2](https://github.com/unarix/haiku_darkstyle/assets/14283509/e70fe07e-24e1-45a8-8ef1-3cf7767f553a)

Regards :-)

**Comment by SolsticeSpectrum** [comment]
Sama issue here on beta4, when compiling using "make", the Decorator is blue. Also ControlLook doesn't work at all in beta4.

**Comment by SolsticeSpectrum** [comment]
@CalebCDE I have a solution, it's bit of a hack but combining Decorator from haiku_extras and compiled ControlLook works.

So what I did was this:
1. Install haiku_extras
2. Move Decorator from `system/add-ons/decorators` to `home/config/non-packaged/add-ons/decorstors`
3. Uninstall haiku_extras
4. Git clone this repo and execute `make` in it
5. Move the compiled ControlLook to `home/config/non-packaged/add-ons/control_look`
6. Apply in Appearance settings

This fixes ControlLook not working and the blue Decorator, everything now works fine in beta4
