### ISSUE TITLE
Themes files are needing some cleaning.

### ISSUE THREAD

**Issue by Briseur** [unarix/haiku_darkstyle#2]
* Themes files contain wrong decorator paths
		window:decor = string("/boot/home/config/non-packaged/add-ons/decorators/FlatDecorator", 63 bytes)

* They also refers to pictures non provided by the package
		// Actual backdrop image file
		be:bgndimginfopath[0] = string("/boot/home/unarix.jpg", 21 bytes)
		be:bgndimginfopath[1] = string("/boot/home/Pictures/wallpaper.png", 33 bytes)

* Substrate screensaver package should be added as dependecy or there should be no mention of it.
	// Screensaver settings
	screensaver_settings = BMessage(0x00000000) {
		// Screensaver active module
		screensaver:modulename = string("Substrate", 9 bytes)

Theme files are basically text files so you can view that using StyledEdit.
Think of using rmatrr, if you view or edit them in a text editor.  Themes files don't have attributes unless packaged.

**Comment by unarix** [comment]
Thanks Briseur!!! Fixed in: 7f8caca. Pictures/screensavers references are delleted.
