### ISSUE TITLE
After reboot, Flat Decorator is shown as Default in Appearance app.

### ISSUE THREAD

**Issue by Briseur** [unarix/haiku_darkstyle#3]
It works but as title says after reboot, it is misidentified as Default.
So to get back to Default setting,i you have to select Flat again in Appearance app then to  close the app and reopen it to select Default.
Maybe it is bacause it is based on Default decorator and you forget to change something?
I didn't test if Control look does that too.

**Comment by Briseur** [comment]
After testing with Be Decorator, it seems to have same problem. So, it could be a problem on Haiku side. https://dev.haiku-os.org/ticket/16412

**Comment by unarix** [comment]
yes, appears to be a problem in haiku... not in the decors/controllook.
