### ISSUE TITLE
Pronounce the border between window content and the window border

### ISSUE THREAD

**Issue by bitigchi** [unarix/haiku_darkstyle#4]
Looking at [this](https://i.imgur.com/Y071FIX.jpg) screenshot, I think I finally figured out how to make the flat look more pleasant.

The reason default ControlLook looks so complete is that there is a clear distinction between the window border and the window content, it's just one big chunky border, so that there is a clear layer. Flat look also has this, but it is not pronounced enough. For instance, the bottom border of the Dooble toolbar looks thicker, but the part it snaps with the window border looks thinner.

I know, this is a bit specific, but thought I should report it. It might be very hard to get, standard Haiku look uses a standard border which looks the same, but using the same outer border in Flat look might be a bit too much. It should be just enough thick that without zooming in, it should look distinct from both sides.

Thanks for your hard work!

**Comment by unarix** [comment]
you are right! Fixed!
