### ISSUE TITLE
Flat decorator cause App server crash after update to hrev54755

### ISSUE THREAD

**Issue by Briseur** [unarix/haiku_darkstyle#7]
After updating to hrev54755, I rebooted and app server crashed leaving me with this in syslog:

 KERN: stack trace, current PC 0x2a281eebb7  _ZN13FlatDecorator10_DrawFrameE5BRect + 0x7:
 KERN:   (0x7f2a03a61150)  0x1fdc0dd706a  _ZN6Window11_DrawBorderEv + 0xea
 KERN:   (0x7f2a03a611c0)  0x1fdc0dd9a0b  _ZN6Window17RedrawDirtyRegionEv + 0x5b
 KERN:   (0x7f2a03a611f0)  0x1fdc0dcaad1  _ZN12ServerWindow14_MessageLooperEv + 0x2a1
 KERN:   (0x7f2a03a61260)  0x1fdc0da898a  _ZN13MessageLooper15_message_threadEPv + 0xa
 KERN:   (0x7f2a03a61270)  0xe0f80c33b9  thread_entry + 0x19

Booting an older state and switching back to default decorator allowed to boot on hrev54755 without error.

Could be caused by https://dev.haiku-os.org/ticket/16638 , see https://dev.haiku-os.org/ticket/16630 for details.

**Comment by unarix** [comment]
Correct @Briseur, fixed. Was necessary update some files in the includes. Recompile it o use the news binaries. thanks!
