### ISSUE TITLE
Flat decorator cause App server crash after update to hrev54775

### ISSUE THREAD

**Issue by Briseur** [unarix/haiku_darkstyle#8]
After updating to hrev54775, I rebooted and app server crashed again leaving me with this in syslog: 

KERN: vm_soft_fault: va 0x41400000 not covered by area in address space
 KERN: vm_page_fault: vm_soft_fault returned error 'Bad address' on fault at 0x41400008, ip 0x1a23a7ffa15, write 1, user 1, thread 0x41b
 KERN: debug_server: Thread 1051 entered the debugger: Segment violation
 KERN: stack trace, current PC 0x1a23a7ffa15  _ZN14BReferenceable16AcquireReferenceEv + 0x5:
 KERN:   (0x7fccea6a8990)  0x163a0255d67  _ZN10ServerFontaSERKS_ + 0x77
 KERN:   (0x7fccea6a89b0)  0x163a02f299e  _ZN15AGGTextRenderer7SetFontERK10ServerFont + 0x2e
 KERN:   (0x7fccea6a8a00)  0x163a02af979  _ZN7Painter7SetFontERK10ServerFont + 0x19
 KERN:   (0x7fccea6a8a20)  0x12166b5937f  _ZN13FlatDecorator10_DrawTitleEPN9Decorator3TabE5BRect + 0x5f
 KERN:   (0x7fccea6a8a90)  0x12166b59157  _ZN13FlatDecorator8_DrawTabEPN9Decorator3TabE5BRect + 0x497
 KERN:   (0x7fccea6a8ba0)  0x163a027b62c  _ZN9Decorator9_DrawTabsE5BRect + 0xac
 KERN:   (0x7fccea6a8c00)  0x163a0282c3f  _ZN12TabDecorator4DrawE5BRect + 0x9f
 KERN:   (0x7fccea6a8c60)  0x163a0274fda  _ZN6Window11_DrawBorderEv + 0xea
 KERN:   (0x7fccea6a8cd0)  0x163a027797b  _ZN6Window17RedrawDirtyRegionEv + 0x5b
 KERN:   (0x7fccea6a8d00)  0x163a0268aa1  _ZN12ServerWindow14_MessageLooperEv + 0x2a1
 KERN:   (0x7fccea6a8d70)  0x163a024698a  _ZN13MessageLooper15_message_threadEPv + 0xa
 KERN:   (0x7fccea6a8d80)  0x18acd91b2e9  thread_entry + 0x19

Again switching back to default decorator allowed to boot on hrev54775 without error.
I guess that you will have to check if there are new files to include and rebuild...

**Comment by Briseur** [comment]
That was due to a fix in deleter see https://dev.haiku-os.org/ticket/16659
Good news is that old binary (prior to hrev54755) is working again.

**Comment by unarix** [comment]
Yes @Briseur, same error here with hrev54755. I already take the changes in deleter.h and rebuild it.

Works again (for now). Thanks!
