### ISSUE TITLE
Stack and Tile (Enhancement)

### ISSUE THREAD

**Issue by DFergFLA** [unarix/haiku_darkstyle#9]
Stack and Tile:

When using the default or Be Decorator the Tab will change color when Stacking or Tiling windows together. This lets the use know that the two windows are close enought to each other. With the Flat Decorator this doesn’t happen, that Tab remains the same color making Stack and Tile difficult to use.

Thanks

Donald

**Comment by unarix** [comment]
Added! try with the new binaries in repository if works ok!

**Comment by DFergFLA** [comment]
Nice!!  :)

Please don't be too mad.  But, I did see a couple problems.  Can't help it.  I'm a software tester all day, everyday.  

The gadgets in the tab itself stay a grey color while the rest of the tab turns yellow.  

Also, and this is less of a deal, but just an observations.  Take a look at the color the tabs turn on the Be and Default decorator.  If possible I think it should stay consistent with the other decorators.  Currently the tabs turn the same shade of yellow as they would if they were active windows.  It took me a moment to realize it was actually working.  

I attempted a video screen capture.  The quality of the recording is rather lacking.  But, I hope it is able to convey what I'm trying to say.

I am now able to use the Flat Decorator with Stack and Tile.  I'm very happy.

I am not able to attach the video file to this thread.  Hopefully the link will work.

[https://drive.google.com/file/d/1qzfb7JVvlHioyyC-uyugpXJR6DF7UiGW/view?usp=sharing](url)

Thanks
